package cn.gdgst.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "activity_exam_list".
 */
public class PeiXun {

    private Long id;
    private String gid;
    private String pid;
    private String title;
    private String img_url;
    private String img_url_s;
    private String video_url;
    private String content;
    private String time;

    public PeiXun() {
    }

    public PeiXun(Long id) {
        this.id = id;
    }

    public PeiXun(Long id, String gid, String pid, String title, String img_url, String img_url_s, String video_url, String content, String time) {
        this.id = id;
        this.gid = gid;
        this.pid = pid;
        this.title = title;
        this.img_url = img_url;
        this.img_url_s = img_url_s;
        this.video_url = video_url;
        this.content = content;
        this.time = time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getGid() {
        return gid;
    }

    public void setGid(String gid) {
        this.gid = gid;
    }

    public String getPid() {
        return pid;
    }

    public void setPid(String pid) {
        this.pid = pid;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getImg_url() {
        return img_url;
    }

    public void setImg_url(String img_url) {
        this.img_url = img_url;
    }

    public String getImg_url_s() {
        return img_url_s;
    }

    public void setImg_url_s(String img_url_s) {
        this.img_url_s = img_url_s;
    }

    public String getVideo_url() {
        return video_url;
    }

    public void setVideo_url(String video_url) {
        this.video_url = video_url;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

}
